### PR TITLE
✨ Add LowerContains support for string fields.

### PR DESCRIPTION
**Pull request by furkandeveloper**
## Summary
This PR includes;
✨ This class generates contains query, for string fields.

## For Example

```csharp
        [ToLowerContainsComparison]
        public string Name { get; set; }
```

- Generated Query is:
```csharp
.Where(x => x.Name.ToLower().Contains(filter.Name.ToLower()))
```

### CODE REVIEW

**Comment by enisn** [comment]
NuGet Push can be ignored. That workflow requires project secrets such as nuget apiKey and source.
✅

**Review by enisn — APPROVED** [review]
Looks great! 🎉

**Review by enisn — CHANGES_REQUESTED** [review]
At least 1 unit test required to accept this PR.
@furkandeveloper

**Review by enisn — APPROVED** [review]

**Comment by furkandeveloper** [comment]
> 
> 
> At least 1 unit test required to accept this PR.
> @furkandeveloper

Can you check commit 42ad90b02857e7ea04847c0e4b98f444ab19848c

**Pull request merged**
